Benchmark
Marusyk/grok.net pull request #21
Opened 2021-08-02 22:44 UTC by halilkocaoz

#13

2021-08-04 21:19 UTC, Marusyk requested changes
Small changes required

2021-08-04 21:19 UTC, Marusyk commented on README.md
> +# Benchmark
Please don't add these to the README

2021-08-04 21:19 UTC, Marusyk commented on benchmark/ParseBenchmark.cs
> +    public class ParseBenchmark
Could you please add MemoryDiagnoser? https://benchmarkdotnet.org/articles/configs/diagnosers.html

2021-08-04 21:19 UTC, Marusyk commented on benchmark/Program.cs
> +        static void Main(string[] args) => BenchmarkRunner.Run<ParseBenchmark>();
It seems we can remove `string[] args`.
Also, please add modifiers to the class and Main method

2021-08-04 21:49 UTC, halilkocaoz commented
Thank you for your time to review and feedback.

2021-08-06 10:40 UTC, Marusyk approved these changes

2021-08-06 10:43 UTC, merged

2021-08-06 10:44 UTC, Marusyk commented
@halilkocaoz  Many thanks for your contribution