Update to .net 6
Marusyk/grok.net pull request #35
Opened 2021-10-03 03:17 UTC by vabka

Use file-scoped namespace everywhere in solution
Add .net5.0 and .net6.0 as targetframeworks
Set langversion to 10

Use some new C# 8 and 9 features (like using-var)

GrokItem could be a record

2021-10-03 21:10 UTC, Marusyk commented
Hi @vabka , thank you for submitting this PR. Will review and update.

2021-10-05 00:13 UTC, Marusyk requested changes
LGTM but small fixes are required

2021-10-05 00:13 UTC, Marusyk commented on src/Grok.Net/Grok.Net.csproj
> +    <PropertyGroup>
Please don't add more spaces. XML files should use indent size equals to 2

2021-10-05 00:13 UTC, Marusyk commented on src/Grok.Net/Grok.cs
> +        if (_compiledRegex == null)
You can use `is null` instead `== null`

2021-10-05 00:13 UTC, Marusyk commented on src/Grok.Net/GrokItem.cs
> +public sealed class GrokItem
Please convert it to a record

2021-11-23 11:21 UTC, vabka commented on src/Grok.Net/Grok.Net.csproj
> +      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
.net 6 is now stable.
Maybe just drop .netstandard and leave .net6 only?

2021-11-23 13:20 UTC, Marusyk commented on src/Grok.Net/Grok.Net.csproj
> +      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
in that case, the package won't available for .net framework applications

2021-12-14 21:02 UTC, Marusyk commented
I'm going to close this PR due to inactivity for a long time

2021-12-14 21:02 UTC, closed without merging